POST http://localhost:3001/api/blogs HTTP/1.1
Content-Type: application/json

# {
#   "title": "Zen Habits",
#   "author": "Leo Babauta",
#   "url": "https://zenhabits.net",
#   "likes": 73
# }
# {
#   "title": "Smitten Kitchen",
#   "author": "Deb Perelman",
#   "url": "https://smittenkitchen.com",
#   "likes": 184
# }
# {
#   "title": "Mr. Money Mustache",
#   "author": "Mr. Money Mustache",
#   "url": "https://www.mrmoneymustache.com",
#   "likes": 92
# }
# {
#   "title": "Seth's Blog",
#   "author": "Seth Godin",
#   "url": "https://seths.blog",
#   "likes": 215
# }
{
  "title": "Designer Daddy",
  "author": "Brent Almond",
  "url": "https://designerdaddy.com",
  "likes": 58
}
